### PR TITLE
add a self-containment test

### LINKED ISSUE #150: Some headers fail to compile independently
I think the previously-fixed Trac ticket [#12228](https://svn.boost.org/trac10/ticket/12228) has regressed.

The [Boost Header Policy](https://www.boost.org/development/header.html) requires:

> Make sure that a translation unit consisting of just the contents of the header file will compile successfully.

Yet, I'm seeing compile errors for quite a few of the headers under Clang and GCC. Eg for `boost/test/data/monomorphic/initializer_list.hpp`:

~~~no-highlight
boost/test/data/monomorphic/initializer_list.hpp:45:27: error: no type named 'vector' in namespace 'std'
    typedef typename std::vector<T>::const_iterator iterator;
            ~~~~~~~~~~~~~~^~~~~~
boost/test/data/monomorphic/initializer_list.hpp:45:33: error: expected member name or ';' after declaration specifiers
    typedef typename std::vector<T>::const_iterator iterator;
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
boost/test/data/monomorphic/initializer_list.hpp:64:5: error: unknown type name 'iterator'
    iterator        begin() const   { return m_data.begin(); }
    ^
boost/test/data/monomorphic/initializer_list.hpp:68:10: error: no template named 'vector' in namespace 'std'
    std::vector<T> m_data;
    ~~~~~^
boost/test/data/monomorphic/initializer_list.hpp:79:18: error: no template named 'vector' in namespace 'std'
    typedef std::vector<bool>::const_iterator iterator;
            ~~~~~^
boost/test/data/monomorphic/initializer_list.hpp:79:32: error: non-friend class member 'const_iterator' cannot have a qualified name
    typedef std::vector<bool>::const_iterator iterator;
                             ~~^
boost/test/data/monomorphic/initializer_list.hpp:79:32: error: typedef declarator cannot be qualified
    typedef std::vector<bool>::const_iterator iterator;
                             ~~^
boost/test/data/monomorphic/initializer_list.hpp:79:46: error: expected ';' at end of declaration list
    typedef std::vector<bool>::const_iterator iterator;
                                             ^
                                             ;
boost/test/data/monomorphic/initializer_list.hpp:96:5: error: unknown type name 'iterator'
    iterator        begin() const   { return m_data.begin(); }
    ^
boost/test/data/monomorphic/initializer_list.hpp:100:10: error: no template named 'vector' in namespace 'std'
    std::vector<bool> m_data;
    ~~~~~^
10 errors generated.
~~~

I think there are problems compiling the following 20 headers:

* `boost/test/data/dataset.hpp`
* `boost/test/data/monomorphic/delayed.hpp`
* `boost/test/data/monomorphic/grid.hpp`
* `boost/test/data/monomorphic.hpp`
* `boost/test/data/monomorphic/initializer_list.hpp`
* `boost/test/data/monomorphic/join.hpp`
* `boost/test/data/monomorphic/zip.hpp`
* `boost/test/data/test_case.hpp`
* `boost/test/tools/collection_comparison_op.hpp`
* `boost/test/tools/detail/lexicographic_manip.hpp`
* `boost/test/tools/detail/per_element_manip.hpp`
* `boost/test/tree/test_case_template.hpp`
* `boost/test/utils/runtime/argument_factory.hpp`
* `boost/test/utils/runtime/cla/argv_traverser.hpp`
* `boost/test/utils/runtime/cla/parser.hpp`
* `boost/test/utils/runtime/env/fetch.hpp`
* `boost/test/utils/runtime/finalize.hpp`
* `boost/test/utils/runtime/modifier.hpp`
* `boost/test/utils/runtime/parameter.hpp`
* `boost/test/utils/xml_printer.hpp`

Thanks for your continued work on this library.

### PR DESCRIPTION
**Pull request by jhunold**
Attempt to fix #150 based on code posted by @swatanabe on the boost mailing list a decade ago.

### CODE REVIEW

**Comment by raffienficiaud** [comment]
Thanks for this! I was wondering how I can implement the approach proposed in #150 !
Will integrate soonish, the build is still red because of the visibility issue.

**Comment by raffienficiaud** [comment]
In `topic/PR-161-self-containment-in-b2`

**Comment by raffienficiaud** [comment]
Merged to develop, thanks!
